---
name: Ivan
surname: Plyushchenko
position: "PhD, postdoctoral research fellow"
address: "Chemistry Department, Lomonosov Moscow State University"
profilepic: test photo.jpg
email: "plyushchenko.ivan@gmail.com"
github: plyush1993
www: orcid.org/0000-0003-3883-4695
date: "`r format(Sys.time(), '%B %Y')`"
docname: CV
output: 
  vitae::twentyseconds
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
library(vitae)
```

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Specialist in Chemistry (equivalent to MSc)", "2011-17", "Lomonosov Moscow State University", "Moscow, Russia",
  "Postgraduate academic and pedagogical training (Chemistry)", "2017-21", "Lomonosov Moscow State University", "Moscow, Russia",
  "Doctor of Philosophy (Chemistry)", "2017-22", "Lomonosov Moscow State University", "Moscow, Russia"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Grants and awards

```{r}
library(tibble)
tribble(
  ~ Award, ~ Year, ~ Place,
  "MSACL EU 2017 Travel Grant", "2017", "Salzburg, Austria",
  "IMSC 2018 Fellowship", "2018", "Florence, Italy",
  "MSACL EU 2019 Travel Grant", "2019", "Salzburg, Austria"
) %>% 
  detailed_entries(Award, Year, Place)
```

# Current journal roles

```{r}
library(tibble)
tribble(
  ~ Journal, ~ Current_journal_roles,
  "Biomedical Chromatography", "Peer Reviewer"
) %>% 
  detailed_entries(with = Current_journal_roles, what = Journal)
```


# Professional Certificates

```{r}
library(tibble)
tribble(
  ~ Certificate, ~ Year, ~ Organization, ~ Hours, 
  "Metabolomics 202: Approaches, Applications and Challenges", "2017", "MSACL EU 2017", "16 hrs",
  "Introduction to R Course", "2018", "DataCamp", "n/a",
  "R Basics - R Programming Language Introduction", "2018", "Udemy", "4 hrs",
  "Data Science 201: Going Further With R: Tackling Clinical Laboratory Data Manipulation and Modeling", "2019", "MSACL EU 2019", "16 hrs",
  "Introduction to programming in R", "2019", "Dataquest", "n/a",
  "Intermediate R programming", "2019", "Dataquest", "n/a",
  "Data visualization in R", "2019", "Dataquest", "n/a",
  "Data analyst in R", "2019", "Dataquest", "n/a",
  "Data cleaning in R", "2019", "Dataquest", "n/a"
) %>% 
  detailed_entries(Certificate, Year, Organization, Hours)
```

# Conferences

```{r}
library(tibble)
tribble(
  ~ Title, ~ Conference, ~ Date,
  "Complexation of sulfo-β-cyclodextrin with fenoterol. Electrophoretic and spectroscopic study", 
  "VIIIth International Symposium Design and Synthesis of Supramolecular Architectures, Kazan, Russia", "2016", 
  "Simple & Robust Approach in Urinary Metabolomics Based on UPLC-MS for Preoperative Colorectal Cancer Diagnostics", "MSACL 2017 EU, Salzburg, Austria", "2017",
  "Typical LC-MS metabolomics workflow for profiling urine samples of patients with colorectal cancer", 
  "XXII International Mass Spectrometry Conference, Florence, Italy", "2018",
  "Comparison of the kinetics of dyes degradation of handwritten strokes subjected to different types of artificial aging and studied using chromatography mass-spectrometry and statistical data processing", 
  "48th International Symposium on High-Performance Liquid Phase Separations and Related Techniques, Milan, Italy", "2019", 
  "Bioassay Classification Study via LC-MS and Machine Learning in Conjunction with Dimensionality Reduction", 
  "MSACL 2019 EU, Salzburg, Austria", "2019",
  "Humulus lupulus LC-MS untargeted profiling study for geographic origin classification task", 
  "4th International Symposium on Phytochemicals in Medicine and Food, Xi'an, China", "2020",
  "Describing metabolome diversity between Humulus lupulus genetic origin groups using UHPLC-MS/MS", 
  "The 69th Annual Conference on Mass Spectrometry of MSSJ, Japan", "2021",
  "Application of gradient boosting machine for signal processing in LC-MS metabolomics", 
  "13th Winter Symposium on Chemometrics, Russia", "2022",
  "Untargeted metabolomics study of Humulus lupulus brewing cultivars, for genetic origin classification task", 
  "13th Winter Symposium on Chemometrics, Russia", "2022"
) %>% 
  detailed_entries(with = Conference, what = Title, when = Date)
```

# Publications

```{r}
library(scholar)
library(tibble)
id <- 'Mz4nxtwAAAAJ'
p1 <- get_publications(id)
p <- p1[,c(2, 1, 3, 6, 4, 5)]
p$cites <- paste0("[Citations: ", p$cites, "]")
p <- p[order(p$year, decreasing = T),]
p <- p[-5,] # delete duplicated Inorganic materials

p %>% 
  detailed_entries(
    what = title,
    when = year,
    with = author,
    where = journal,
    why = cites
  )

```

### Publications list was generated by Google Scholar (https://scholar.google.com/citations?hl=user=Mz4nxtwAAAAJ)